#!/usr/bin/env zsh
for i in dbip-chunks/dbip-chunk-*
do
	id=`echo $i|cut -d '-' -f4`
	echo "init slice ${id}"
	curl "https://cypherpunk.com/api/v0/network/secretGeoDatabaseInit?chunk=${id}" &
	sleep 15
done
