#!/usr/bin/env zsh
for i in dbip-chunks/dbip-chunk-*
do
	id=`echo $i|cut -d '-' -f4`
	echo "init slice ${id}"
	curl "https://cypherpunk.engineering/api/frontend/secretGeoDatabaseInit?chunk=${id}" &
	sleep 10
done
