/**
 * Server-side routes. Only the listed routes support html5pushstate.
 * Has to match client side routes.
 *
 * Index (/) route does not have to be listed here.
 *
 * @example
 * export const routes: string[] = [
 * 'home', 'about'
 * ];
 **/
export const routes: string[] = [
  'home',
  'account',
  'account/billing',
  'account/upgrade',
  'account/setup',
  'account/reset',
  'pricing',
  'login',
  'recover',
  'download/*',
  'confirm',
  'why-use-a-vpn',
  'features',
  'network',
  'privacy-policy',
  'about-us',
  'terms-of-service',
  'blog',
  'blog/post/*',
  '404',
  'apps',
  'apps/browser',
  'apps/mac',
  'apps/windows',
  'apps/ios',
  'apps/android',
  'apps/linux',
  'apps/routers',
  'feedback',
  'bounty',
  'whats-my-ip-address',
  'signup',
  'reset',
  'support',
  'support/articles',
  'support/articles/*',
  'support/tutorials',
  'support/tutorials/*',
  'support/windows',
  'support/windows/*',
  'support/mac',
  'support/mac/*',
  'support/macos',
  'support/macos/*',
  'support/linux',
  'support/linux/*',
  'support/android',
  'support/android/*',
  'support/ios',
  'support/ios/*',
  'support/browsers',
  'support/browsers/*',
  'support/windows-phone',
  'support/windows-phone/*',
  'support/routers',
  'support/routers/*',
  'support/others',
  'support/others/*',
  'support/request/new',
  'partial/hostname',
  'partial/credentials',
  'partial/cert',
  'partial/config-generator',
  'partial/google-play',
  'partial/amazon-app-store',
  'partial/itunes'
];
