runtime: python27
threadsafe: true
api_version: 1

default_expiration: "1m"

handlers: # should be ordered from most specific to least specific
- url: /(.*\.(appcache|manifest))
  mime_type: text/cache-manifest
  static_files: content/\1
  upload: content/(.*\.(appcache|manifest))
  expiration: "0m"
  http_headers:
    Strict-Transport-Security: max-age=13370000; includeSubDomains; preload
  #login: required

- url: /(.*\.atom)
  mime_type: application/atom+xml
  static_files: content/\1
  upload: content/(.*\.atom)
  expiration: "1h"
  http_headers:
    Strict-Transport-Security: max-age=13370000; includeSubDomains; preload
  #login: required

- url: /(.*\.crx)
  mime_type: application/x-chrome-extension
  static_files: content/\1
  upload: content/(.*\.crx)
  http_headers:
    Strict-Transport-Security: max-age=13370000; includeSubDomains; preload
  #login: required

- url: /(.*\.css)
  mime_type: text/css
  static_files: content/\1
  upload: content/(.*\.css)
  http_headers:
    Strict-Transport-Security: max-age=13370000; includeSubDomains; preload
  #login: required

- url: /(.*\.eot)
  mime_type: application/vnd.ms-fontobject
  static_files: content/\1
  upload: content/(.*\.eot)
  http_headers:
    Strict-Transport-Security: max-age=13370000; includeSubDomains; preload
  #login: required

- url: /(.*\.htc)
  mime_type: text/x-component
  static_files: content/\1
  upload: content/(.*\.htc)
  http_headers:
    Strict-Transport-Security: max-age=13370000; includeSubDomains; preload
  #login: required

- url: /(.*\.html)
  mime_type: text/html
  static_files: content/\1
  upload: content/(.*\.html)
  expiration: "1m"
  http_headers:
    Strict-Transport-Security: max-age=13370000; includeSubDomains; preload
  #login: required

- url: /(.*\.ico)
  mime_type: image/x-icon
  static_files: content/\1
  upload: content/(.*\.ico)
  expiration: "1d"
  http_headers:
    Strict-Transport-Security: max-age=13370000; includeSubDomains; preload
  #login: required

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: content/\1
  upload: content/(.*\.js)
  http_headers:
    Strict-Transport-Security: max-age=13370000; includeSubDomains; preload
  #login: required

- url: /(.*\.json)
  mime_type: application/json
  static_files: content/\1
  upload: content/(.*\.json)
  expiration: "1h"
  http_headers:
    Strict-Transport-Security: max-age=13370000; includeSubDomains; preload
  #login: required

- url: /(.*\.m4v)
  mime_type: video/m4v
  static_files: content/\1
  upload: content/(.*\.m4v)
  http_headers:
    Strict-Transport-Security: max-age=13370000; includeSubDomains; preload
  #login: required

- url: /(.*\.mp4)
  mime_type: video/mp4
  static_files: content/\1
  upload: content/(.*\.mp4)
  http_headers:
    Strict-Transport-Security: max-age=13370000; includeSubDomains; preload
  #login: required

- url: /(.*\.(ogg|oga))
  mime_type: audio/ogg
  static_files: content/\1
  upload: content/(.*\.(ogg|oga))
  http_headers:
    Strict-Transport-Security: max-age=13370000; includeSubDomains; preload
  #login: required

- url: /(.*\.ogv)
  mime_type: video/ogg
  static_files: content/\1
  upload: content/(.*\.ogv)
  http_headers:
    Strict-Transport-Security: max-age=13370000; includeSubDomains; preload
  #login: required

- url: /(.*\.otf)
  mime_type: font/opentype
  static_files: content/\1
  upload: content/(.*\.otf)
  http_headers:
    Strict-Transport-Security: max-age=13370000; includeSubDomains; preload
  #login: required

- url: /(.*\.rss)
  mime_type: application/rss+xml
  static_files: content/\1
  upload: content/(.*\.rss)
  expiration: "1h"
  http_headers:
    Strict-Transport-Security: max-age=13370000; includeSubDomains; preload
  #login: required

- url: /(.*\.safariextz)
  mime_type: application/octet-stream
  static_files: content/\1
  upload: content/(.*\.safariextz)
  http_headers:
    Strict-Transport-Security: max-age=13370000; includeSubDomains; preload
  #login: required

- url: /(.*\.(svg|svgz))
  mime_type: images/svg+xml
  static_files: content/\1
  upload: content/(.*\.(svg|svgz))
  http_headers:
    Strict-Transport-Security: max-age=13370000; includeSubDomains; preload
  #login: required

- url: /(.*\.swf)
  mime_type: application/x-shockwave-flash
  static_files: content/\1
  upload: content/(.*\.swf)
  http_headers:
    Strict-Transport-Security: max-age=13370000; includeSubDomains; preload
  #login: required

- url: /(.*\.ttf)
  mime_type: font/truetype
  static_files: content/\1
  upload: content/(.*\.ttf)
  http_headers:
    Strict-Transport-Security: max-age=13370000; includeSubDomains; preload
  #login: required

- url: /(.*\.txt)
  mime_type: text/plain
  static_files: content/\1
  upload: content/(.*\.txt)
  http_headers:
    Strict-Transport-Security: max-age=13370000; includeSubDomains; preload
  #login: required

- url: /(.*\.unity3d)
  mime_type: application/vnd.unity
  static_files: content/\1
  upload: content/(.*\.unity3d)
  http_headers:
    Strict-Transport-Security: max-age=13370000; includeSubDomains; preload
  #login: required

- url: /(.*\.webm)
  mime_type: video/webm
  static_files: content/\1
  upload: content/(.*\.webm)
  http_headers:
    Strict-Transport-Security: max-age=13370000; includeSubDomains; preload
  #login: required

- url: /(.*\.webp)
  mime_type: image/webp
  static_files: content/\1
  upload: content/(.*\.webp)
  http_headers:
    Strict-Transport-Security: max-age=13370000; includeSubDomains; preload
  #login: required

- url: /(.*\.woff)
  mime_type: application/x-font-woff
  static_files: content/\1
  upload: content/(.*\.woff)
  http_headers:
    Strict-Transport-Security: max-age=13370000; includeSubDomains; preload
  #login: required

- url: /(.*\.xml)
  mime_type: application/xml
  static_files: content/\1
  upload: content/(.*\.xml)
  expiration: "1h"
  http_headers:
    Strict-Transport-Security: max-age=13370000; includeSubDomains; preload
  #login: required

- url: /(.*\.xpi)
  mime_type: application/x-xpinstall
  static_files: content/\1
  upload: content/(.*\.xpi)
  http_headers:
    Strict-Transport-Security: max-age=13370000; includeSubDomains; preload
  #login: required

# image files
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: content/\1
  upload: content/(.*\.(bmp|gif|ico|jpeg|jpg|png))
  http_headers:
    Strict-Transport-Security: max-age=13370000; includeSubDomains; preload
  #login: required

# audio files
- url: /(.*\.(mid|midi|mp3|wav))
  static_files: content/\1
  upload: content/(.*\.(mid|midi|mp3|wav))
  http_headers:
    Strict-Transport-Security: max-age=13370000; includeSubDomains; preload
  #login: required

# windows files
- url: /(.*\.(doc|exe|ppt|rtf|xls))
  static_files: content/\1
  upload: content/(.*\.(doc|exe|ppt|rtf|xls))
  http_headers:
    Strict-Transport-Security: max-age=13370000; includeSubDomains; preload
  #login: required

# compressed files
- url: /(.*\.(bz2|gz|rar|tar|tgz|zip))
  static_files: content/\1
  upload: content/(.*\.(bz2|gz|rar|tar|tgz|zip))
  http_headers:
    Strict-Transport-Security: max-age=13370000; includeSubDomains; preload
  #login: required

# index files
- url: /(.+)/
  static_files: content/\1.html
  upload: content/(.+).html
  expiration: "1m"
  http_headers:
    Strict-Transport-Security: max-age=13370000; includeSubDomains; preload
  #login: required

- url: /(.+)
  static_files: content/\1.html
  upload: content/(.+).html
  expiration: "1m"
  http_headers:
    Strict-Transport-Security: max-age=13370000; includeSubDomains; preload
  #login: required

# site root
- url: /
  static_files: content/cypherpunk-public.html
  upload: content/cypherpunk-public.html
  expiration: "15m"
  http_headers:
    Strict-Transport-Security: max-age=13370000; includeSubDomains; preload
  #login: required
